---
title: "Charlie Duff ca4_query"
output: pdf_document
date: "2023-01-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Download and load libraries

if(!require("DBI"))
  install.packages("DBI")
if(!require("dplyr"))
  install.packages("dplyr")
# if(!require("readr"))
#   install.packages("readr")

library(DBI)
#library(readr)
library(dplyr)


```




```{r include=FALSE}
## Establish a connection to the MySQL DB
conn = dbConnect(RMySQL::MySQL(),
                            dbname='sql8589433',
                            host='sql8.freesqldatabase.com',
                            port=3306,
                            user='sql8589433',
                            password = rstudioapi::askForPassword("Enter database password"))
```



```{r echo=FALSE}
## Test the remote connection
dbListTables(conn)
dbListFields(conn, "Employees")
```



```{sql connection=conn, include=FALSE, output.var="projects"}
## Use an SQL chunk to query and store the results
SELECT * FROM Projects
```

```{r echo=FALSE}
## Accessing the results in an R chunk
projects
```

##Selecting Distinct Values
```{sql connection=conn, include=FALSE, output.var="disjobs"}
## Use an SQL chunk to query and store the results
SELECT DISTINCT Employees_employeeName FROM ProjectJobs
```

```{r echo=FALSE}
## Accessing the results of projects_daterange
##projects_daterange

knitr::kable(head(disjobs), "simple")
```


##Selecting Across Date Range
```{sql connection=conn, include=FALSE, output.var="projects_daterange"}
## Use an SQL chunk to query and store the results
SELECT projectID,projectName,startDate,finishDate FROM Projects WHERE startDate > "2023-01-01" && startDate < "2023-01-17"
```

```{r echo=FALSE}
## Accessing the results of projects_daterange
##projects_daterange

knitr::kable(head(projects_daterange[, 1:4]), "simple")
```


```{r include=FALSE}
## Do NOT forget to disconnect - otherwise we may hit a remote connection limit

dbDisconnect(conn)
```
